name: raust
description: Rede de alertas comunitários para desastres e emergências (estilo Waze expandido)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  llamadart: ^0.6.15
  path_provider: ^2.1.4
  shared_preferences: ^2.3.0
  image_picker: ^1.1.2
  uuid: ^4.5.0
  intl: ^0.19.0
  geolocator: ^13.0.1          # Para pegar localização
  flutter_markdown: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
